### ISSUE TITLE
종료시 멈춤현상

### ISSUE THREAD

**Issue by dolsoon** [isingmodel/UI_typing_recorder#3]
.csv 파일은 잘 생성이 됩니다.
그런데, pyqt ui가 깔끔하게 종료가 안되고 응답없음 상태로 되네요. 왜 이런걸까요?

<img width="396" alt="err" src="https://user-images.githubusercontent.com/35393343/85238393-85a4f400-b468-11ea-9c09-112a4cec9a6e.PNG">

**Comment by isingmodel** [comment]
Fixed on https://github.com/isingmodel/UI_typing_recorder/commit/63e1c1687cb4eb1c23aad0f0db008e0df73da907
