### ISSUE TITLE
python을 모르는 사람도

### ISSUE THREAD

**Issue by dolsoon** [isingmodel/UI_typing_recorder#4]
1. python을 모르는 사람도 실행할 수 있도록
2. 보안프로그램을 우회할 수 있도록

업데이트 가능할까요?

**Comment by isingmodel** [comment]
보안 프로그램 우회는 어떤 것을 말씀하시는 건가요?

**Comment by dolsoon** [comment]
왜 저번에 말씀하신 것 있잖아요
mini python?
간이 python?
이름이 생각이 안나는데 가벼운 파이썬으로 python코드를 실행하도록 하면 우회할 수 있을 것 같다고 하셨잖아요

**Comment by isingmodel** [comment]
Done.
